# Generated by Django 5.2.3 on 2025-07-25 10:26

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/admin/profile_default.png', upload_to=users.models.profile_image_path),
        ),
    ]
